**Importation des données**

In [4]:
import pandas as pd
from IPython.display import display

df1 = pd.read_excel("Ventes_Février_2025.xlsx")
df2 = pd.read_excel("Ventes_Janvier_2025.xlsx")
df3 = pd.read_excel("Ventes_Mars_2025.xlsx")
df4 = pd.read_excel("Referentiels_Projet.xlsx")

**Analyse et Nettoyage**

In [10]:
display(df1.isnull().sum())

Vente_ID          0
Date_Vente        0
Client_ID         1
Client            0
Produit_ID        0
Produit           1
Catégorie         0
Quantité          1
Prix_Unitaire     0
Remise            0
Montant           0
Région            1
Segment_Client    0
Statut_Source     0
dtype: int64

In [13]:
lignes_manquante = df1[df1.isnull().any(axis=1)]

display(lignes_manquante)

,Vente_ID,Date_Vente,Client_ID,Client,Produit_ID,Produit,Catégorie,Quantité,Prix_Unitaire,Remise,Montant,Région,Segment_Client,Statut_Source
400,V20250200401,2025-02-25 19:50:27,C0052,Client Z2,P008,Produit H,Mode,NaN,29.04,0.00,145.20,Hauts-de-France,B2B,OK
550,V20250200551,2025-02-27 13:28:59,C0096,Client R4,P002,Produit B,Électronique,10.0,14.05,0.05,133.47,NaN,B2C,OK
850,V20250200851,2025-02-28 13:59:25,C0020,Client T1,P006,NaN,Maison,11.0,171.76,0.10,1700.42,Grand Est,B2B,OK
1200,V20250201201,2025-02-09 18:11:20,NaN,Client K3,P012,Produit L,Sport,11.0,130.30,0.00,1433.30,Occitanie,PME,OK

In [ ]:
mask_qte = (
    df1["Quantité"].isna()
   &df1["Montant"].notna()
   &df1["Prix_Unitaire"].notna()
   &df1["Remise"].notna()
)

df1.loc[mask_qte, "Quantité"] = (
    df1.loc[mask_qte, "Montant"] /(
    df1.loc[mask_qte, "Prix_Unitaire"]*
    (1-df1.loc[mask_qte, "Remise"])
    )
)

In [43]:
df1["Région"] = df1["Région"].fillna("Auvergne-Rhône-Alpes")

In [30]:
df1["Produit"] = df1["Produit"].fillna("Produit F")

In [37]:
df1["Client_ID"] = df1["Client_ID"].fillna("C0063")

In [38]:
display(df1.isnull().sum())

Vente_ID          0
Date_Vente        0
Client_ID         0
Client            0
Produit_ID        0
Produit           0
Catégorie         0
Quantité          0
Prix_Unitaire     0
Remise            0
Montant           0
Région            0
Segment_Client    0
Statut_Source     0
Clienr_ID         0
dtype: int64

In [40]:
df1.to_excel("Ventes_Février_2025_clean.xlsx", index=False)

In [26]:
ref_file = "Referentiels_Projet.xlsx"

excel_ref = pd.ExcelFile(ref_file)

print(excel_ref.sheet_names)

['Clients', 'Produits']

In [27]:
clients = pd.read_excel(
    "Referentiels_Projet.xlsx",
    sheet_name="Clients"
)

produits = pd.read_excel(
    "Referentiels_Projet.xlsx",
    sheet_name="Produits"
)

print("Clients :")
display(clients.head())

print("\nProduits :")
display(produits.head())

Clients :

  Client_ID     Client                Région       Segment
0     C0001  Client A1       Hauts-de-France  Grand compte
1     C0002  Client B1  Auvergne-Rhône-Alpes  Grand compte
2     C0003  Client C1       Hauts-de-France           PME
3     C0004  Client D1         Île-de-France           B2C
4     C0005  Client E1             Occitanie  Grand compte

Produits :

  Produit_ID    Produit     Catégorie  Prix_Unitaire
0       P001  Produit A  Électronique         162.74
1       P002  Produit B  Électronique          14.05
2       P003  Produit C  Électronique          74.56
3       P004  Produit D        Maison          62.02
4       P005  Produit E        Maison         186.23

In [15]:
display(df2.isnull().sum())

Vente_ID          0
Date_Vente        0
Client_ID         1
Client            0
Produit_ID        0
Produit           1
Catégorie         0
Quantité          1
Prix_Unitaire     0
Remise            0
Montant           0
Région            1
Segment_Client    0
Statut_Source     0
dtype: int64

In [16]:
lignes_manquante_2 = df2[df2.isnull().any(axis=1)]

display(lignes_manquante_2)

,Vente_ID,Date_Vente,Client_ID,Client,Produit_ID,Produit,Catégorie,Quantité,Prix_Unitaire,Remise,Montant,Région,Segment_Client,Statut_Source
400,V20250100401,2025-01-17 10:26:10,C0046,Client T2,P009,Produit I,Mode,NaN,110.11,0.15,1310.31,Grand Est,B2C,OK
550,V20250100551,2025-01-25 18:37:49,C0063,Client K3,P002,Produit B,Électronique,8.0,14.05,0.00,112.40,NaN,PME,OK
850,V20250100851,2025-01-19 14:14:42,C0012,Client L1,P005,NaN,Maison,3.0,186.23,0.05,530.76,Île-de-France,Grand compte,OK
1200,V20250101201,2025-01-14 18:14:54,NaN,Client P4,P011,Produit K,Sport,2.0,60.91,0.00,121.82,Île-de-France,B2C,OK

In [41]:
mask_qte2= (
    df2["Quantité"].isna()
   &df2["Montant"].notna()
   &df2["Prix_Unitaire"].notna()
   &df2["Remise"].notna()
)

df2.loc[mask_qte, "Quantité"] = (
    df2.loc[mask_qte, "Montant"] /(
    df2.loc[mask_qte, "Prix_Unitaire"]*
    (1-df1.loc[mask_qte, "Remise"])
    )
)

In [44]:
df2["Région"] = df2["Région"].fillna("Occitanie")

In [45]:
df2["Produit"] = df2["Produit"].fillna("Produit E")

In [46]:
df2["Client_ID"] = df2["Client_ID"].fillna("C0094")

In [48]:
df2.to_excel("Ventes_Janvier_2025_clean.xlsx",index=False)

In [47]:
display(df2.isnull().sum())

Vente_ID          0
Date_Vente        0
Client_ID         0
Client            0
Produit_ID        0
Produit           0
Catégorie         0
Quantité          0
Prix_Unitaire     0
Remise            0
Montant           0
Région            0
Segment_Client    0
Statut_Source     0
dtype: int64

In [18]:
display(df3.isnull().sum())

Vente_ID          0
Date_Vente        0
Client_ID         1
Client            0
Produit_ID        0
Produit           1
Catégorie         0
Quantité          1
Prix_Unitaire     0
Remise            0
Montant           0
Région            1
Segment_Client    0
Statut_Source     0
dtype: int64

In [20]:
lignes_manquantes_3 = df3[df3.isnull().any(axis=1)]

display(lignes_manquantes_3)

,Vente_ID,Date_Vente,Client_ID,Client,Produit_ID,Produit,Catégorie,Quantité,Prix_Unitaire,Remise,Montant,Région,Segment_Client,Statut_Source
400,V20250300401,2025-03-17 19:14:18,C0099,Client U4,P003,Produit C,Électronique,NaN,74.56,0.05,566.66,Nouvelle-Aquitaine,B2C,OK
550,V20250300551,2025-03-03 22:54:46,C0067,Client O3,P005,Produit E,Maison,4.0,186.23,0.00,744.92,NaN,B2C,OK
850,V20250300851,2025-03-24 16:48:48,C0025,Client Y1,P014,NaN,Beauté,5.0,56.12,0.10,252.54,Grand Est,B2C,OK
1200,V20250301201,2025-03-27 08:22:47,NaN,Client J4,P006,Produit F,Maison,9.0,171.76,0.00,1545.84,Hauts-de-France,B2C,OK

In [53]:
mask_qte3 = (
    df3["Quantité"].isna()
    &df3["Montant"].notna()
    &df3["Prix_Unitaire"].notna()
    &df3["Remise"].notna()
)
df3.loc[mask_qte3,"Quantité"] = (
    df3.loc[mask_qte3,"Montant"] /
    (df3.loc[mask_qte3,"Prix_Unitaire"] *
    (1-df3.loc[mask_qte3,"Remise"])
    )
)

In [54]:
df3["Région"] = df3["Région"].fillna("Occitanie")

In [55]:
df3["Produit"] = df3["Produit"].fillna("Produit N")

In [56]:
df3["Client_ID"] = df3["Client_ID"].fillna("C0088")

In [58]:
df3.to_excel("Ventes_Mars_2025_clean.xlsx", index=False)

In [21]:
display(df4.isnull().sum())

Client_ID    0
Client       0
Région       0
Segment      0
dtype: int64